nathanielhf-comp2084-assignment-1/Models/Item.cs
namespace nathanielhf_comp2084_assignment_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Item
    {
        [Key]
        public int item_id { get; set; }

        public int department_id { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name="Item Name")]
        public string name { get; set; }

        [StringLength(1024)]
        [Display(Name ="Image")]
        public string image { get; set; }
        
        [Display(Name ="Price")]
        [Column(TypeName = "numeric")]
        [Range(0,1000, ErrorMessage = "Please enter a price between 0-1000")]
        [DataType(DataType.Currency)]
        public decimal price { get; set; }

        public virtual Department Department { get; set; }
    }
}

nathanielhf-comp2084-assignment-1/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using nathanielhf_comp2084_assignment_1.Models;

namespace nathanielhf_comp2084_assignment_1.Controllers
{
    [Authorize]
    public class ItemsController : Controller
    {
        private GroceryListModel db = new GroceryListModel();

        [AllowAnonymous]
        // GET: Items
        public ActionResult Index()
        {
            var items = db.Items.Include(i => i.Department);
            return View(items.ToList());
        }

        [AllowAnonymous]
        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            ViewBag.department_id = new SelectList(db.Departments, "department_id", "name");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "item_id,department_id,name,image,price")] Item item)
        {
            if (ModelState.IsValid)
            {
                // upload image if there is one
                if (Request.Files.Count > 0)
                {
                    var file = Request.Files[0];

                    if (file.FileName != null && file.ContentLength > 0)
                    {
                        // get file path dynamically
                        string path = Server.MapPath("~/Content/Images/") + file.FileName;
                        file.SaveAs(path);

                        item.image = "/Content/Images/" + file.FileName;
                    }
                }

                db.Items.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.department_id = new SelectList(db.Departments, "department_id", "name", item.department_id);
            return View(item);
        }

        // GET: Items/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            ViewBag.department_id = new SelectList(db.Departments, "department_id", "name", item.department_id);
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "item_id,department_id,name,image,price")] Item item)
        {
            if (ModelState.IsValid)
            {
                // upload image if there is one
                if (Request.Files.Count > 0)
                {
                    var file = Request.Files[0];

                    if (file.FileName != null && file.ContentLength > 0)
                    {
                        // get file path dynamically
                        string path = Server.MapPath("~/Content/Images/") + file.FileName;
                        file.SaveAs(path);

                        item.image = "/Content/Images/" + file.FileName;
                    }
                }

                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.department_id = new SelectList(db.Departments, "department_id", "name", item.department_id);
            return View(item);
        }

        // GET: Items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.Items.Find(id);
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

nathanielhf-comp2084-assignment-1/Views/Items/Create.cshtml
@model nathanielhf_comp2084_assignment_1.Models.Item

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Items", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.department_id, "Department", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("department_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.department_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="image" id="image" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="tan-btn btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="make-btn-here">
    @Html.ActionLink("Back to List", "Index")
</div>

nathanielhf-comp2084-assignment-1/Views/Items/Delete.cshtml
@model nathanielhf_comp2084_assignment_1.Models.Item

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Department.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="tan-btn btn btn-default" /> 
            <div class="make-btn-here" style="margin-top: 10px">@Html.ActionLink("Back to List", "Index")</div>
        </div>
    }
</div>

nathanielhf-comp2084-assignment-1/Views/Items/Details.cshtml
@model nathanielhf_comp2084_assignment_1.Models.Item

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>@Html.DisplayFor(model => model.name)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Department.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

    </dl>
</div>
<p>
    @if(User.Identity.IsAuthenticated) { 
        @Html.ActionLink("Edit", "Edit", new { id = Model.item_id })  
    }
    @Html.ActionLink("Back to List", "Index")
</p>

nathanielhf-comp2084-assignment-1/Views/Items/Edit.cshtml
@model nathanielhf_comp2084_assignment_1.Models.Item

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Items", FormMethod.Post, new { @enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Html.DisplayFor(model => model.name)</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.item_id)

        <div class="form-group">
            @Html.LabelFor(model => model.department_id, "Department", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("department_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.department_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="no-btn" type="file" name="image" id="image" />
                <img src="@Model.image" title="@Model.name" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="tan-btn btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="make-btn-here">
    @Html.ActionLink("Back to List", "Index")
</div>

nathanielhf-comp2084-assignment-1/Views/Items/Index.cshtml
@model IEnumerable<nathanielhf_comp2084_assignment_1.Models.Item>

@{
    ViewBag.Title = "Items";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Items</h2>

@if(User.Identity.IsAuthenticated) { 
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Department.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Department.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            <img src="@item.image" alt="@item.name" width="75"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.price)
        </td>
        <td>
            @if(User.Identity.IsAuthenticated) { 
                @Html.ActionLink("Edit", "Edit", new { id=item.item_id })  
            }
            @Html.ActionLink("Details", "Details", new { id=item.item_id })  
            @if(User.Identity.IsAuthenticated) { 
                @Html.ActionLink("Delete", "Delete", new { id=item.item_id })
            }
        </td>
    </tr>
}

</table>